export const BIRD_CATEGORIES = [
  { id: 36, name: '4K专区', icon: '4k' },
  { id: 10, name: '美女', icon: 'person' },
  { id: 30, name: '游戏', icon: 'sports_esports' },
  { id: 9, name: '风景', icon: 'landscape' },
  { id: 15, name: '动漫', icon: 'animation' },
  { id: 26, name: '汽车', icon: 'directions_car' },
  { id: 14, name: '动物', icon: 'pets' },
  { id: 12, name: '影视', icon: 'movie' },
  { id: 5, name: '明星', icon: 'star' },
  { id: 13, name: '军事', icon: 'military_tech' },
  { id: 21, name: '体育', icon: 'sports_soccer' },
  { id: 29, name: '财经', icon: 'attach_money' },
  { id: 35, name: '炫彩视觉', icon: 'palette' },
  { id: 33, name: '物语', icon: 'auto_stories' },
  { id: 32, name: '设计', icon: 'design_services' },
  { id: 16, name: '文字', icon: 'text_fields' },
  { id: 11, name: '情感', icon: 'favorite' },
  { id: 27, name: '节日', icon: 'celebration' },
];
